# Generated by Django 4.1.10 on 2023-08-18 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMemeLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления лайка')),
                ('group_meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meme_likes', to='groups.groupmeme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='groupmeme',
            name='likes',
            field=models.ManyToManyField(related_name='meme_groups_like', through='groups.GroupMemeLike', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
        migrations.AddConstraint(
            model_name='groupmemelike',
            constraint=models.UniqueConstraint(fields=('group_meme', 'user'), name='unique_group_meme_like'),
        ),
    ]
