# Generated by Django 4.1.7 on 2023-06-21 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_grouprole_is_admin_grouprole_is_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmeme',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_meme_added_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
