# Generated by Django 4.1.9 on 2023-06-26 13:22

from django.db import migrations, models
import django.db.models.deletion
import groups.models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_groupmeme_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupuser',
            name='role',
            field=models.ForeignKey(default=groups.models.GroupRole.get_default_role, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='users', to='groups.grouprole'),
        ),
    ]
