version: '3.8'

services:
  frontend: 
    image: artkeyplex/frontend-generator-meme:latest
    volumes: 
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  postgres:
    image: postgres:14.4-alpine
    volumes:
      - /pg_data/:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  backend:
    image: artkeyplex/generator-meme:latest
    restart: always
    volumes:
      - /data/static/:/app/backend-static/
      - /data/media/:/app/backend-media/
      - /data/:/add/data/
    depends_on:
      - postgres
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-old.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - /data/static/:/var/html/backend-static/
      - /data/media/:/var/html/backend-media/
    depends_on:
      - backend
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
