version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  redis:
    image: 'redis:7.2'
    restart: always
    expose:
      - "6379"

  postgres:
    image: postgres:14.4-alpine
    volumes:
      - meme_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  # pgadmin:
  #   container_name: pgadmin
  #   restart: always
  #   image: dpage/pgadmin4
  #   volumes:
  #     - pgadmin_data:/var/lib/pgadmin
  #   env_file:
  #     - ./.env

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - static_value:/app/backend-static/
      - media_value:/app/backend-media/
      - email_dev_data:/app/sent_emails/
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - postgres
    env_file:
      - ./.env
    # extra_hosts:
    # - "host.docker.internal:host-gateway"

  ws:
    build:
      context: ../backend
      dockerfile: DockerfileWS
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx-dev.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/backend-static/
      - media_value:/var/html/backend-media/
    depends_on:
      - backend

volumes:
  static_value:
  media_value:
  meme_data:
  # pgadmin_data:
  email_dev_data:
