# Generated by Django 2.2.16 on 2023-02-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0002_auto_20230212_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
