# Generated by Django 4.1.7 on 2023-02-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0003_template_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meme',
            options={'verbose_name': 'Готовый мем', 'verbose_name_plural': 'Готовые мемы'},
        ),
        migrations.AddField(
            model_name='template',
            name='name',
            field=models.CharField(blank=True, default='Шаблон', max_length=100, verbose_name='Название шаблона'),
        ),
        migrations.AlterField(
            model_name='template',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Статус публикации'),
        ),
    ]
