# Generated by Django 4.1.7 on 2023-02-28 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0005_alter_template_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ('created_at',), 'verbose_name': 'Шаблон мема', 'verbose_name_plural': 'Шаблоны мемов'},
        ),
        migrations.AlterField(
            model_name='favorite',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='memes.template', verbose_name='Избранный шаблон'),
        ),
    ]
