# Generated by Django 4.1.7 on 2023-04-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0007_alter_template_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='is_trash',
            field=models.BooleanField(default=False, verbose_name='Trash'),
        ),
        migrations.AlterField(
            model_name='template',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='memes', to='memes.tag', verbose_name='Теги'),
        ),
    ]
