# Generated by Django 4.1.7 on 2023-04-08 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0008_template_is_trash_alter_template_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='is_trash',
        ),
    ]
