# Generated by Django 4.1.7 on 2023-04-18 22:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0009_remove_template_is_trash'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateUsedTimes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('used_times', models.IntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_used_times', to='memes.template', verbose_name='Использован раз')),
            ],
        ),
    ]
