# Generated by Django 4.1.7 on 2023-06-05 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0013_category_template_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
