# Generated by Django 4.1.9 on 2023-06-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0015_alter_template_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='published_at',
            field=models.DateTimeField(null=True, verbose_name='Дата публикации на сайт'),
        ),
        migrations.AlterField(
            model_name='template',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки в базу'),
        ),
    ]
