# Generated by Django 4.1.10 on 2023-08-08 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memes', '0017_alter_template_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('is_author', models.BooleanField(default=False, verbose_name='Собственный мем')),
                ('meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='memes.meme', verbose_name='Мем')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Коллекция мемов',
                'verbose_name_plural': 'Коллекции мемов',
                'ordering': ('-added_at',),
            },
        ),
    ]
