# Generated by Django 4.1.10 on 2023-08-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0018_usercollection'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usercollection',
            constraint=models.UniqueConstraint(fields=('user', 'meme'), name='unique_user_meme'),
        ),
    ]
