version: '3.3'
services:
  proxy:
    image: nginx:1.19.3
    volumes:
      - ./proxy-nginx.conf:/etc/nginx/conf.d/default.conf
      - /root/data/certbot/conf:/etc/letsencrypt
      - /root/data/certbot/www:/var/www/certbot
    networks:
      - site
      - test
    ports:
      - "80:80"
      - "443:443"

networks:
  site:
    name: site_default
    external: true
  test:
    name: test_default
    external: true