# Generated by Django 4.1.7 on 2023-06-08 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTeammate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Teammate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Максимум 300 символов', max_length=300, verbose_name='Имя')),
                ('description', models.CharField(blank=True, help_text='Максимум 300 символов', max_length=300, verbose_name='Описание')),
                ('link', models.CharField(blank=True, help_text='Максимум 300 символов', max_length=300, verbose_name='Ссылка')),
                ('active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
                'ordering': ('-active', 'name'),
            },
        ),
        migrations.CreateModel(
            name='TeamGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Максимум 300 символов', max_length=300, verbose_name='Название')),
                ('level', models.IntegerField(help_text='Чем меньше цифра, тем выше в выводе информации будет эта группа', verbose_name='Уровень')),
                ('teammates', models.ManyToManyField(related_name='teammates', through='team.GroupTeammate', to='team.teammate', verbose_name='Ингредиенты')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ('level', 'name'),
            },
        ),
        migrations.AddField(
            model_name='groupteammate',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='team.teamgroup'),
        ),
        migrations.AddField(
            model_name='groupteammate',
            name='teammate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teammate', to='team.teammate'),
        ),
        migrations.AddConstraint(
            model_name='groupteammate',
            constraint=models.UniqueConstraint(fields=('group', 'teammate'), name='unique_group_teammate'),
        ),
    ]
