# Generated by Django 4.1.10 on 2023-08-08 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=3), django.core.validators.RegexValidator(message='Поле должно содержать только допустимые символы', regex='^[a-zA-Zа-яА-ЯёЁ0-9 !@#$%^&*(_)\\-=\\+]+$')], verbose_name='Имя пользователя'),
        ),
    ]
