name: Backup

on:
  schedule:
    - cron: '0 0 */3 * *' # каждые 3 дня будет срабатывать

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create backup
        run: |
          cd backup/
          docker exec -t root_postgres_1 pg_dumpall -c -U postgres > dump_`date +%d-%m-%Y"_"%H_%M_%S`.sql
      - name: Upload backup
        uses: actions/upload-artifact@v2
        with:
          name: backup
          path: dump_`date +%d-%m-%Y"_"%H_%M_%S`.sql
