name: secrets

on:
  push:
    branches: [ "backend_load_images_fix" ]

jobs:
  make_file:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd infra
            touch secrets.txt
            echo DB_ENGINE=${{ secrets.DB_ENGINE }} >> secrets.txt
            echo DEFAULT_FROM_EMAIL=${{ secrets.DEFAULT_FROM_EMAIL }} >> secrets.txt
            echo DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }} >> secrets.txt
            echo DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }} >> secrets.txt
            echo EMAIL_HOST=${{ secrets.EMAIL_HOST }} >> secrets.txt
            echo EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }} >> secrets.txt
            echo EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }} >> secrets.txt
            echo HOST=${{ secrets.HOST }} >> secrets.txt
            echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> secrets.txt
            echo SOCIAL_AUTH_GOOGLE_OAUTH2_KEY=${{ secrets.SOCIAL_AUTH_GOOGLE_OAUTH2_KEY }} >> secrets.txt
            echo SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET=${{ secrets.SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET }} >> secrets.txt
            echo SOCIAL_AUTH_TELEGRAM_BOT_TOKEN=${{ secrets.SOCIAL_AUTH_TELEGRAM_BOT_TOKEN }} >> secrets.txt
            echo SOCIAL_AUTH_VK_OAUTH2_KEY=${{ secrets.SOCIAL_AUTH_VK_OAUTH2_KEY }} >> secrets.txt
            echo SOCIAL_AUTH_VK_OAUTH2_SECRET=${{ secrets.SOCIAL_AUTH_VK_OAUTH2_SECRET }} >> secrets.txt
            echo SOCIAL_AUTH_YANDEX_OAUTH2_KEY=${{ secrets.SOCIAL_AUTH_YANDEX_OAUTH2_KEY }} >> secrets.txt
            echo SOCIAL_AUTH_YANDEX_OAUTH2_SECRET=${{ secrets.SOCIAL_AUTH_YANDEX_OAUTH2_SECRET }} >> secrets.txt
            echo SSH_KEY=${{ secrets.SSH_KEY }} >> secrets.txt
            echo TELEGRAM_TO=${{ secrets.TELEGRAM_TO }} >> secrets.txt
            echo TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }} >> secrets.txt
            echo TEST_DOMAIN=${{ secrets.TEST_DOMAIN }} >> secrets.txt
            echo TEST_POSTGRES_DB=${{ secrets.TEST_POSTGRES_DB }} >> secrets.txt
            echo TEST_POSTGRES_HOST=${{ secrets.TEST_POSTGRES_HOST }} >> secrets.txt
            echo TEST_POSTGRES_PASSWORD=${{ secrets.TEST_POSTGRES_PASSWORD }} >> secrets.txt
            echo TEST_POSTGRES_PORT=${{ secrets.TEST_POSTGRES_PORT }} >> secrets.txt
            echo TEST_POSTGRES_USER=${{ secrets.TEST_POSTGRES_USER }} >> secrets.txt
            echo USER=${{ secrets.USER }} >> secrets.txt
            echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> secrets.txt
            echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> secrets.txt
            echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> secrets.txt
            echo POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} >> secrets.txt
            echo POSTGRES_PORT=${{ secrets.POSTGRES_PORT }} >> secrets.txt
            echo DOMAIN=${{ secrets.DOMAIN }} >> secrets.txt
            echo EMAIL=${{ secrets.EMAIL }} >> secrets.txt
            echo PASSWORD=${{ secrets.PASSWORD }} >> secrets.txt
            echo PGADMIN_DEFAULT_EMAIL=${{ secrets.PGADMIN_DEFAULT_EMAIL }} >> secrets.txt
            echo PGADMIN_DEFAULT_PASSWORD=${{ secrets.PGADMIN_DEFAULT_PASSWORD }} >> secrets.txt